### ISSUE TITLE
Fallback to built-in regex module

### ISSUE THREAD

**Issue by iurisilvio** [dimka665/awesome-slugify#20]
The `regex` module does not support pypy.

**Comment by jamadden** [comment]
I reported this to the authors of `regex` in [issue #135](https://code.google.com/p/mrab-regex-hg/issues/detail?id=135), and provided a fix. It hasn't been incorporated, though. So for now, we're maintaining [a branch](https://github.com/NextThought/mrab-regex-hg/tree/pypy) that does include the fix. It is directly installable from buildout and probably from pip.

**Comment by iurisilvio** [comment]
Thanks for your effort to make it work! I will try it soon!

**Comment by iurisilvio** [comment]
I tried and worked fine. I was able to deploy my service with PyPy and it reduced my response times in 30%. Thanks!

**Comment by jamadden** [comment]
The author of `regex` reports that the necessary patch has [been released](https://code.google.com/p/mrab-regex-hg/issues/detail?id=135#c6) to PyPI as [version 2015.05.07](https://pypi.python.org/pypi/regex) (although I haven't tried that yet).
